#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Inmmokraft")]
	public partial class DataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttblDatos(tblDatos instance);
    partial void UpdatetblDatos(tblDatos instance);
    partial void DeletetblDatos(tblDatos instance);
    partial void InserttblUsuario(tblUsuario instance);
    partial void UpdatetblUsuario(tblUsuario instance);
    partial void DeletetblUsuario(tblUsuario instance);
    partial void InserttblGrupos(tblGrupos instance);
    partial void UpdatetblGrupos(tblGrupos instance);
    partial void DeletetblGrupos(tblGrupos instance);
    partial void InserttblPagina(tblPagina instance);
    partial void UpdatetblPagina(tblPagina instance);
    partial void DeletetblPagina(tblPagina instance);
    partial void InserttblTipoUsuario(tblTipoUsuario instance);
    partial void UpdatetblTipoUsuario(tblTipoUsuario instance);
    partial void DeletetblTipoUsuario(tblTipoUsuario instance);
    #endregion
		
		public DataBaseDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.InmmokraftConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblDatos> tblDatos
		{
			get
			{
				return this.GetTable<tblDatos>();
			}
		}
		
		public System.Data.Linq.Table<tblUsuario> tblUsuario
		{
			get
			{
				return this.GetTable<tblUsuario>();
			}
		}
		
		public System.Data.Linq.Table<tblGrupos> tblGrupos
		{
			get
			{
				return this.GetTable<tblGrupos>();
			}
		}
		
		public System.Data.Linq.Table<tblPagina> tblPagina
		{
			get
			{
				return this.GetTable<tblPagina>();
			}
		}
		
		public System.Data.Linq.Table<tblTipoUsuario> tblTipoUsuario
		{
			get
			{
				return this.GetTable<tblTipoUsuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDatos")]
	public partial class tblDatos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDato;
		
		private System.Nullable<int> _idUsuario;
		
		private System.Nullable<int> _idPagina;
		
		private System.Nullable<int> _idGrupo;
		
		private string _datPerfil;
		
		private string _datPropiedad;
		
		private string _datTipo;
		
		private System.Data.Linq.Binary _datArte;
		
		private string _datTituloArte;
		
		private System.Nullable<System.DateTime> _datFechaHoraPub;
		
		private string _datSitio;
		
		private System.Nullable<int> _datGrupoPost;
		
		private System.Nullable<System.DateTime> _datContInteresado;
		
		private System.Nullable<int> _datCantInteresado;
		
		private System.Nullable<System.DateTime> _datContramensaje;
		
		private System.Nullable<int> _datCantRecibidos;
		
		private string _datLlamadaFinal;
		
		private System.Nullable<System.DateTime> _datCita;
		
		private System.Nullable<char> _datEstado;
		
		private EntityRef<tblUsuario> _tblUsuario;
		
		private EntityRef<tblGrupos> _tblGrupos;
		
		private EntityRef<tblPagina> _tblPagina;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDatoChanging(int value);
    partial void OnidDatoChanged();
    partial void OnidUsuarioChanging(System.Nullable<int> value);
    partial void OnidUsuarioChanged();
    partial void OnidPaginaChanging(System.Nullable<int> value);
    partial void OnidPaginaChanged();
    partial void OnidGrupoChanging(System.Nullable<int> value);
    partial void OnidGrupoChanged();
    partial void OndatPerfilChanging(string value);
    partial void OndatPerfilChanged();
    partial void OndatPropiedadChanging(string value);
    partial void OndatPropiedadChanged();
    partial void OndatTipoChanging(string value);
    partial void OndatTipoChanged();
    partial void OndatArteChanging(System.Data.Linq.Binary value);
    partial void OndatArteChanged();
    partial void OndatTituloArteChanging(string value);
    partial void OndatTituloArteChanged();
    partial void OndatFechaHoraPubChanging(System.Nullable<System.DateTime> value);
    partial void OndatFechaHoraPubChanged();
    partial void OndatSitioChanging(string value);
    partial void OndatSitioChanged();
    partial void OndatGrupoPostChanging(System.Nullable<int> value);
    partial void OndatGrupoPostChanged();
    partial void OndatContInteresadoChanging(System.Nullable<System.DateTime> value);
    partial void OndatContInteresadoChanged();
    partial void OndatCantInteresadoChanging(System.Nullable<int> value);
    partial void OndatCantInteresadoChanged();
    partial void OndatContramensajeChanging(System.Nullable<System.DateTime> value);
    partial void OndatContramensajeChanged();
    partial void OndatCantRecibidosChanging(System.Nullable<int> value);
    partial void OndatCantRecibidosChanged();
    partial void OndatLlamadaFinalChanging(string value);
    partial void OndatLlamadaFinalChanged();
    partial void OndatCitaChanging(System.Nullable<System.DateTime> value);
    partial void OndatCitaChanged();
    partial void OndatEstadoChanging(System.Nullable<char> value);
    partial void OndatEstadoChanged();
    #endregion
		
		public tblDatos()
		{
			this._tblUsuario = default(EntityRef<tblUsuario>);
			this._tblGrupos = default(EntityRef<tblGrupos>);
			this._tblPagina = default(EntityRef<tblPagina>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDato", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDato
		{
			get
			{
				return this._idDato;
			}
			set
			{
				if ((this._idDato != value))
				{
					this.OnidDatoChanging(value);
					this.SendPropertyChanging();
					this._idDato = value;
					this.SendPropertyChanged("idDato");
					this.OnidDatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int")]
		public System.Nullable<int> idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._tblUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPagina", DbType="Int")]
		public System.Nullable<int> idPagina
		{
			get
			{
				return this._idPagina;
			}
			set
			{
				if ((this._idPagina != value))
				{
					if (this._tblPagina.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPaginaChanging(value);
					this.SendPropertyChanging();
					this._idPagina = value;
					this.SendPropertyChanged("idPagina");
					this.OnidPaginaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGrupo", DbType="Int")]
		public System.Nullable<int> idGrupo
		{
			get
			{
				return this._idGrupo;
			}
			set
			{
				if ((this._idGrupo != value))
				{
					if (this._tblGrupos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidGrupoChanging(value);
					this.SendPropertyChanging();
					this._idGrupo = value;
					this.SendPropertyChanged("idGrupo");
					this.OnidGrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datPerfil", DbType="VarChar(100)")]
		public string datPerfil
		{
			get
			{
				return this._datPerfil;
			}
			set
			{
				if ((this._datPerfil != value))
				{
					this.OndatPerfilChanging(value);
					this.SendPropertyChanging();
					this._datPerfil = value;
					this.SendPropertyChanged("datPerfil");
					this.OndatPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datPropiedad", DbType="VarChar(100)")]
		public string datPropiedad
		{
			get
			{
				return this._datPropiedad;
			}
			set
			{
				if ((this._datPropiedad != value))
				{
					this.OndatPropiedadChanging(value);
					this.SendPropertyChanging();
					this._datPropiedad = value;
					this.SendPropertyChanged("datPropiedad");
					this.OndatPropiedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datTipo", DbType="VarChar(100)")]
		public string datTipo
		{
			get
			{
				return this._datTipo;
			}
			set
			{
				if ((this._datTipo != value))
				{
					this.OndatTipoChanging(value);
					this.SendPropertyChanging();
					this._datTipo = value;
					this.SendPropertyChanged("datTipo");
					this.OndatTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datArte", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary datArte
		{
			get
			{
				return this._datArte;
			}
			set
			{
				if ((this._datArte != value))
				{
					this.OndatArteChanging(value);
					this.SendPropertyChanging();
					this._datArte = value;
					this.SendPropertyChanged("datArte");
					this.OndatArteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datTituloArte", DbType="VarChar(50)")]
		public string datTituloArte
		{
			get
			{
				return this._datTituloArte;
			}
			set
			{
				if ((this._datTituloArte != value))
				{
					this.OndatTituloArteChanging(value);
					this.SendPropertyChanging();
					this._datTituloArte = value;
					this.SendPropertyChanged("datTituloArte");
					this.OndatTituloArteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datFechaHoraPub", DbType="DateTime")]
		public System.Nullable<System.DateTime> datFechaHoraPub
		{
			get
			{
				return this._datFechaHoraPub;
			}
			set
			{
				if ((this._datFechaHoraPub != value))
				{
					this.OndatFechaHoraPubChanging(value);
					this.SendPropertyChanging();
					this._datFechaHoraPub = value;
					this.SendPropertyChanged("datFechaHoraPub");
					this.OndatFechaHoraPubChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datSitio", DbType="VarChar(100)")]
		public string datSitio
		{
			get
			{
				return this._datSitio;
			}
			set
			{
				if ((this._datSitio != value))
				{
					this.OndatSitioChanging(value);
					this.SendPropertyChanging();
					this._datSitio = value;
					this.SendPropertyChanged("datSitio");
					this.OndatSitioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datGrupoPost", DbType="Int")]
		public System.Nullable<int> datGrupoPost
		{
			get
			{
				return this._datGrupoPost;
			}
			set
			{
				if ((this._datGrupoPost != value))
				{
					this.OndatGrupoPostChanging(value);
					this.SendPropertyChanging();
					this._datGrupoPost = value;
					this.SendPropertyChanged("datGrupoPost");
					this.OndatGrupoPostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datContInteresado", DbType="DateTime")]
		public System.Nullable<System.DateTime> datContInteresado
		{
			get
			{
				return this._datContInteresado;
			}
			set
			{
				if ((this._datContInteresado != value))
				{
					this.OndatContInteresadoChanging(value);
					this.SendPropertyChanging();
					this._datContInteresado = value;
					this.SendPropertyChanged("datContInteresado");
					this.OndatContInteresadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datCantInteresado", DbType="Int")]
		public System.Nullable<int> datCantInteresado
		{
			get
			{
				return this._datCantInteresado;
			}
			set
			{
				if ((this._datCantInteresado != value))
				{
					this.OndatCantInteresadoChanging(value);
					this.SendPropertyChanging();
					this._datCantInteresado = value;
					this.SendPropertyChanged("datCantInteresado");
					this.OndatCantInteresadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datContramensaje", DbType="DateTime")]
		public System.Nullable<System.DateTime> datContramensaje
		{
			get
			{
				return this._datContramensaje;
			}
			set
			{
				if ((this._datContramensaje != value))
				{
					this.OndatContramensajeChanging(value);
					this.SendPropertyChanging();
					this._datContramensaje = value;
					this.SendPropertyChanged("datContramensaje");
					this.OndatContramensajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datCantRecibidos", DbType="Int")]
		public System.Nullable<int> datCantRecibidos
		{
			get
			{
				return this._datCantRecibidos;
			}
			set
			{
				if ((this._datCantRecibidos != value))
				{
					this.OndatCantRecibidosChanging(value);
					this.SendPropertyChanging();
					this._datCantRecibidos = value;
					this.SendPropertyChanged("datCantRecibidos");
					this.OndatCantRecibidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datLlamadaFinal", DbType="VarChar(100)")]
		public string datLlamadaFinal
		{
			get
			{
				return this._datLlamadaFinal;
			}
			set
			{
				if ((this._datLlamadaFinal != value))
				{
					this.OndatLlamadaFinalChanging(value);
					this.SendPropertyChanging();
					this._datLlamadaFinal = value;
					this.SendPropertyChanged("datLlamadaFinal");
					this.OndatLlamadaFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datCita", DbType="DateTime")]
		public System.Nullable<System.DateTime> datCita
		{
			get
			{
				return this._datCita;
			}
			set
			{
				if ((this._datCita != value))
				{
					this.OndatCitaChanging(value);
					this.SendPropertyChanging();
					this._datCita = value;
					this.SendPropertyChanged("datCita");
					this.OndatCitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datEstado", DbType="Char(1)")]
		public System.Nullable<char> datEstado
		{
			get
			{
				return this._datEstado;
			}
			set
			{
				if ((this._datEstado != value))
				{
					this.OndatEstadoChanging(value);
					this.SendPropertyChanging();
					this._datEstado = value;
					this.SendPropertyChanged("datEstado");
					this.OndatEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUsuario_tblDatos", Storage="_tblUsuario", ThisKey="idUsuario", OtherKey="idUsuario", IsForeignKey=true)]
		public tblUsuario tblUsuario
		{
			get
			{
				return this._tblUsuario.Entity;
			}
			set
			{
				tblUsuario previousValue = this._tblUsuario.Entity;
				if (((previousValue != value) 
							|| (this._tblUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUsuario.Entity = null;
						previousValue.tblDatos.Remove(this);
					}
					this._tblUsuario.Entity = value;
					if ((value != null))
					{
						value.tblDatos.Add(this);
						this._idUsuario = value.idUsuario;
					}
					else
					{
						this._idUsuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblUsuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGrupos_tblDatos", Storage="_tblGrupos", ThisKey="idGrupo", OtherKey="idGrupo", IsForeignKey=true)]
		public tblGrupos tblGrupos
		{
			get
			{
				return this._tblGrupos.Entity;
			}
			set
			{
				tblGrupos previousValue = this._tblGrupos.Entity;
				if (((previousValue != value) 
							|| (this._tblGrupos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblGrupos.Entity = null;
						previousValue.tblDatos.Remove(this);
					}
					this._tblGrupos.Entity = value;
					if ((value != null))
					{
						value.tblDatos.Add(this);
						this._idGrupo = value.idGrupo;
					}
					else
					{
						this._idGrupo = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblGrupos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPagina_tblDatos", Storage="_tblPagina", ThisKey="idPagina", OtherKey="idPagina", IsForeignKey=true)]
		public tblPagina tblPagina
		{
			get
			{
				return this._tblPagina.Entity;
			}
			set
			{
				tblPagina previousValue = this._tblPagina.Entity;
				if (((previousValue != value) 
							|| (this._tblPagina.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPagina.Entity = null;
						previousValue.tblDatos.Remove(this);
					}
					this._tblPagina.Entity = value;
					if ((value != null))
					{
						value.tblDatos.Add(this);
						this._idPagina = value.idPagina;
					}
					else
					{
						this._idPagina = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblPagina");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUsuario")]
	public partial class tblUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuario;
		
		private System.Nullable<int> _idTipUsu;
		
		private string _usNombre;
		
		private string _usApellido;
		
		private string _usCedula;
		
		private string _usClave;
		
		private string _usCorreo;
		
		private string _usDireccion;
		
		private System.Nullable<char> _usEstado;
		
		private EntitySet<tblDatos> _tblDatos;
		
		private EntityRef<tblTipoUsuario> _tblTipoUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnidTipUsuChanging(System.Nullable<int> value);
    partial void OnidTipUsuChanged();
    partial void OnusNombreChanging(string value);
    partial void OnusNombreChanged();
    partial void OnusApellidoChanging(string value);
    partial void OnusApellidoChanged();
    partial void OnusCedulaChanging(string value);
    partial void OnusCedulaChanged();
    partial void OnusClaveChanging(string value);
    partial void OnusClaveChanged();
    partial void OnusCorreoChanging(string value);
    partial void OnusCorreoChanged();
    partial void OnusDireccionChanging(string value);
    partial void OnusDireccionChanged();
    partial void OnusEstadoChanging(System.Nullable<char> value);
    partial void OnusEstadoChanged();
    #endregion
		
		public tblUsuario()
		{
			this._tblDatos = new EntitySet<tblDatos>(new Action<tblDatos>(this.attach_tblDatos), new Action<tblDatos>(this.detach_tblDatos));
			this._tblTipoUsuario = default(EntityRef<tblTipoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipUsu", DbType="Int")]
		public System.Nullable<int> idTipUsu
		{
			get
			{
				return this._idTipUsu;
			}
			set
			{
				if ((this._idTipUsu != value))
				{
					if (this._tblTipoUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipUsuChanging(value);
					this.SendPropertyChanging();
					this._idTipUsu = value;
					this.SendPropertyChanged("idTipUsu");
					this.OnidTipUsuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usNombre", DbType="VarChar(50)")]
		public string usNombre
		{
			get
			{
				return this._usNombre;
			}
			set
			{
				if ((this._usNombre != value))
				{
					this.OnusNombreChanging(value);
					this.SendPropertyChanging();
					this._usNombre = value;
					this.SendPropertyChanged("usNombre");
					this.OnusNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usApellido", DbType="VarChar(50)")]
		public string usApellido
		{
			get
			{
				return this._usApellido;
			}
			set
			{
				if ((this._usApellido != value))
				{
					this.OnusApellidoChanging(value);
					this.SendPropertyChanging();
					this._usApellido = value;
					this.SendPropertyChanged("usApellido");
					this.OnusApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usCedula", DbType="VarChar(50)")]
		public string usCedula
		{
			get
			{
				return this._usCedula;
			}
			set
			{
				if ((this._usCedula != value))
				{
					this.OnusCedulaChanging(value);
					this.SendPropertyChanging();
					this._usCedula = value;
					this.SendPropertyChanged("usCedula");
					this.OnusCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usClave", DbType="VarChar(50)")]
		public string usClave
		{
			get
			{
				return this._usClave;
			}
			set
			{
				if ((this._usClave != value))
				{
					this.OnusClaveChanging(value);
					this.SendPropertyChanging();
					this._usClave = value;
					this.SendPropertyChanged("usClave");
					this.OnusClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usCorreo", DbType="VarChar(50)")]
		public string usCorreo
		{
			get
			{
				return this._usCorreo;
			}
			set
			{
				if ((this._usCorreo != value))
				{
					this.OnusCorreoChanging(value);
					this.SendPropertyChanging();
					this._usCorreo = value;
					this.SendPropertyChanged("usCorreo");
					this.OnusCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usDireccion", DbType="VarChar(50)")]
		public string usDireccion
		{
			get
			{
				return this._usDireccion;
			}
			set
			{
				if ((this._usDireccion != value))
				{
					this.OnusDireccionChanging(value);
					this.SendPropertyChanging();
					this._usDireccion = value;
					this.SendPropertyChanged("usDireccion");
					this.OnusDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usEstado", DbType="Char(1)")]
		public System.Nullable<char> usEstado
		{
			get
			{
				return this._usEstado;
			}
			set
			{
				if ((this._usEstado != value))
				{
					this.OnusEstadoChanging(value);
					this.SendPropertyChanging();
					this._usEstado = value;
					this.SendPropertyChanged("usEstado");
					this.OnusEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUsuario_tblDatos", Storage="_tblDatos", ThisKey="idUsuario", OtherKey="idUsuario")]
		public EntitySet<tblDatos> tblDatos
		{
			get
			{
				return this._tblDatos;
			}
			set
			{
				this._tblDatos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTipoUsuario_tblUsuario", Storage="_tblTipoUsuario", ThisKey="idTipUsu", OtherKey="idTipUsu", IsForeignKey=true)]
		public tblTipoUsuario tblTipoUsuario
		{
			get
			{
				return this._tblTipoUsuario.Entity;
			}
			set
			{
				tblTipoUsuario previousValue = this._tblTipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._tblTipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTipoUsuario.Entity = null;
						previousValue.tblUsuario.Remove(this);
					}
					this._tblTipoUsuario.Entity = value;
					if ((value != null))
					{
						value.tblUsuario.Add(this);
						this._idTipUsu = value.idTipUsu;
					}
					else
					{
						this._idTipUsu = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblTipoUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDatos(tblDatos entity)
		{
			this.SendPropertyChanging();
			entity.tblUsuario = this;
		}
		
		private void detach_tblDatos(tblDatos entity)
		{
			this.SendPropertyChanging();
			entity.tblUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblGrupos")]
	public partial class tblGrupos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idGrupo;
		
		private System.Nullable<int> _idPagina;
		
		private string _grupNombre;
		
		private string _grupAcceso;
		
		private string _grupEstado;
		
		private EntitySet<tblDatos> _tblDatos;
		
		private EntityRef<tblPagina> _tblPagina;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidGrupoChanging(int value);
    partial void OnidGrupoChanged();
    partial void OnidPaginaChanging(System.Nullable<int> value);
    partial void OnidPaginaChanged();
    partial void OngrupNombreChanging(string value);
    partial void OngrupNombreChanged();
    partial void OngrupAccesoChanging(string value);
    partial void OngrupAccesoChanged();
    partial void OngrupEstadoChanging(string value);
    partial void OngrupEstadoChanged();
    #endregion
		
		public tblGrupos()
		{
			this._tblDatos = new EntitySet<tblDatos>(new Action<tblDatos>(this.attach_tblDatos), new Action<tblDatos>(this.detach_tblDatos));
			this._tblPagina = default(EntityRef<tblPagina>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGrupo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idGrupo
		{
			get
			{
				return this._idGrupo;
			}
			set
			{
				if ((this._idGrupo != value))
				{
					this.OnidGrupoChanging(value);
					this.SendPropertyChanging();
					this._idGrupo = value;
					this.SendPropertyChanged("idGrupo");
					this.OnidGrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPagina", DbType="Int")]
		public System.Nullable<int> idPagina
		{
			get
			{
				return this._idPagina;
			}
			set
			{
				if ((this._idPagina != value))
				{
					if (this._tblPagina.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPaginaChanging(value);
					this.SendPropertyChanging();
					this._idPagina = value;
					this.SendPropertyChanged("idPagina");
					this.OnidPaginaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupNombre", DbType="VarChar(100)")]
		public string grupNombre
		{
			get
			{
				return this._grupNombre;
			}
			set
			{
				if ((this._grupNombre != value))
				{
					this.OngrupNombreChanging(value);
					this.SendPropertyChanging();
					this._grupNombre = value;
					this.SendPropertyChanged("grupNombre");
					this.OngrupNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupAcceso", DbType="VarChar(100)")]
		public string grupAcceso
		{
			get
			{
				return this._grupAcceso;
			}
			set
			{
				if ((this._grupAcceso != value))
				{
					this.OngrupAccesoChanging(value);
					this.SendPropertyChanging();
					this._grupAcceso = value;
					this.SendPropertyChanged("grupAcceso");
					this.OngrupAccesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupEstado", DbType="VarChar(100)")]
		public string grupEstado
		{
			get
			{
				return this._grupEstado;
			}
			set
			{
				if ((this._grupEstado != value))
				{
					this.OngrupEstadoChanging(value);
					this.SendPropertyChanging();
					this._grupEstado = value;
					this.SendPropertyChanged("grupEstado");
					this.OngrupEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGrupos_tblDatos", Storage="_tblDatos", ThisKey="idGrupo", OtherKey="idGrupo")]
		public EntitySet<tblDatos> tblDatos
		{
			get
			{
				return this._tblDatos;
			}
			set
			{
				this._tblDatos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPagina_tblGrupos", Storage="_tblPagina", ThisKey="idPagina", OtherKey="idPagina", IsForeignKey=true)]
		public tblPagina tblPagina
		{
			get
			{
				return this._tblPagina.Entity;
			}
			set
			{
				tblPagina previousValue = this._tblPagina.Entity;
				if (((previousValue != value) 
							|| (this._tblPagina.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPagina.Entity = null;
						previousValue.tblGrupos.Remove(this);
					}
					this._tblPagina.Entity = value;
					if ((value != null))
					{
						value.tblGrupos.Add(this);
						this._idPagina = value.idPagina;
					}
					else
					{
						this._idPagina = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblPagina");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDatos(tblDatos entity)
		{
			this.SendPropertyChanging();
			entity.tblGrupos = this;
		}
		
		private void detach_tblDatos(tblDatos entity)
		{
			this.SendPropertyChanging();
			entity.tblGrupos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPagina")]
	public partial class tblPagina : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPagina;
		
		private string _sitNombre;
		
		private string _sitAutor;
		
		private EntitySet<tblDatos> _tblDatos;
		
		private EntitySet<tblGrupos> _tblGrupos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPaginaChanging(int value);
    partial void OnidPaginaChanged();
    partial void OnsitNombreChanging(string value);
    partial void OnsitNombreChanged();
    partial void OnsitAutorChanging(string value);
    partial void OnsitAutorChanged();
    #endregion
		
		public tblPagina()
		{
			this._tblDatos = new EntitySet<tblDatos>(new Action<tblDatos>(this.attach_tblDatos), new Action<tblDatos>(this.detach_tblDatos));
			this._tblGrupos = new EntitySet<tblGrupos>(new Action<tblGrupos>(this.attach_tblGrupos), new Action<tblGrupos>(this.detach_tblGrupos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPagina", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPagina
		{
			get
			{
				return this._idPagina;
			}
			set
			{
				if ((this._idPagina != value))
				{
					this.OnidPaginaChanging(value);
					this.SendPropertyChanging();
					this._idPagina = value;
					this.SendPropertyChanged("idPagina");
					this.OnidPaginaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitNombre", DbType="VarChar(100)")]
		public string sitNombre
		{
			get
			{
				return this._sitNombre;
			}
			set
			{
				if ((this._sitNombre != value))
				{
					this.OnsitNombreChanging(value);
					this.SendPropertyChanging();
					this._sitNombre = value;
					this.SendPropertyChanged("sitNombre");
					this.OnsitNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitAutor", DbType="VarChar(100)")]
		public string sitAutor
		{
			get
			{
				return this._sitAutor;
			}
			set
			{
				if ((this._sitAutor != value))
				{
					this.OnsitAutorChanging(value);
					this.SendPropertyChanging();
					this._sitAutor = value;
					this.SendPropertyChanged("sitAutor");
					this.OnsitAutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPagina_tblDatos", Storage="_tblDatos", ThisKey="idPagina", OtherKey="idPagina")]
		public EntitySet<tblDatos> tblDatos
		{
			get
			{
				return this._tblDatos;
			}
			set
			{
				this._tblDatos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPagina_tblGrupos", Storage="_tblGrupos", ThisKey="idPagina", OtherKey="idPagina")]
		public EntitySet<tblGrupos> tblGrupos
		{
			get
			{
				return this._tblGrupos;
			}
			set
			{
				this._tblGrupos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDatos(tblDatos entity)
		{
			this.SendPropertyChanging();
			entity.tblPagina = this;
		}
		
		private void detach_tblDatos(tblDatos entity)
		{
			this.SendPropertyChanging();
			entity.tblPagina = null;
		}
		
		private void attach_tblGrupos(tblGrupos entity)
		{
			this.SendPropertyChanging();
			entity.tblPagina = this;
		}
		
		private void detach_tblGrupos(tblGrupos entity)
		{
			this.SendPropertyChanging();
			entity.tblPagina = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTipoUsuario")]
	public partial class tblTipoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipUsu;
		
		private string _tusuRol;
		
		private System.Nullable<char> _tusuEstado;
		
		private EntitySet<tblUsuario> _tblUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipUsuChanging(int value);
    partial void OnidTipUsuChanged();
    partial void OntusuRolChanging(string value);
    partial void OntusuRolChanged();
    partial void OntusuEstadoChanging(System.Nullable<char> value);
    partial void OntusuEstadoChanged();
    #endregion
		
		public tblTipoUsuario()
		{
			this._tblUsuario = new EntitySet<tblUsuario>(new Action<tblUsuario>(this.attach_tblUsuario), new Action<tblUsuario>(this.detach_tblUsuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipUsu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTipUsu
		{
			get
			{
				return this._idTipUsu;
			}
			set
			{
				if ((this._idTipUsu != value))
				{
					this.OnidTipUsuChanging(value);
					this.SendPropertyChanging();
					this._idTipUsu = value;
					this.SendPropertyChanged("idTipUsu");
					this.OnidTipUsuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusuRol", DbType="VarChar(50)")]
		public string tusuRol
		{
			get
			{
				return this._tusuRol;
			}
			set
			{
				if ((this._tusuRol != value))
				{
					this.OntusuRolChanging(value);
					this.SendPropertyChanging();
					this._tusuRol = value;
					this.SendPropertyChanged("tusuRol");
					this.OntusuRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusuEstado", DbType="Char(1)")]
		public System.Nullable<char> tusuEstado
		{
			get
			{
				return this._tusuEstado;
			}
			set
			{
				if ((this._tusuEstado != value))
				{
					this.OntusuEstadoChanging(value);
					this.SendPropertyChanging();
					this._tusuEstado = value;
					this.SendPropertyChanged("tusuEstado");
					this.OntusuEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTipoUsuario_tblUsuario", Storage="_tblUsuario", ThisKey="idTipUsu", OtherKey="idTipUsu")]
		public EntitySet<tblUsuario> tblUsuario
		{
			get
			{
				return this._tblUsuario;
			}
			set
			{
				this._tblUsuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblUsuario(tblUsuario entity)
		{
			this.SendPropertyChanging();
			entity.tblTipoUsuario = this;
		}
		
		private void detach_tblUsuario(tblUsuario entity)
		{
			this.SendPropertyChanging();
			entity.tblTipoUsuario = null;
		}
	}
}
#pragma warning restore 1591
